apiVersion: v1
kind: Service
metadata:
  name: {{ include "nacos-server.fullname" . }}
  labels:
    {{- include "nacos-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8848
      protocol: TCP
  selector:
    {{- include "nacos-server.selectorLabels" . | nindent 4 }}
